In [8]:
# Imports
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from bs4 import BeautifulSoup
import pandas as pd
from time import sleep
import numpy as np
import itertools
from IPython.core.display import display, HTML
display(HTML('<style>.container {width:100% !important; }</style>'))

In [9]:

def finviz_scrape(symbol):
    retry_count = itertools.count()
    print(symbol)
    driver=None
    while True: # initate search
        try:
            sleep(.25)
            driver = webdriver.Chrome() # open chrome
            driver.get('https://finviz.com/')
            
            #########################################
            #########################################
            
#             message me on LinkedIn for the code! 
#             I would like to grow my network. Thanks!

            #########################################
            #########################################
            
            df=pd.DataFrame(info)
            df['symbol'] = symbol
            driver.quit() # close chrome
            return df
            break
        except: # if stock has no recorded insider trading
            if next(retry_count) <= 0: # search again, just to be sure
                print('not there, try again')
                driver.quit()
            else: # breakout
                driver.quit()
                print('not found')
                break

In [10]:
symbol='airt' # Air T Corporation
inside_trading =finviz_scrape(symbol)

airt

In [11]:
inside_trading

,0,1,2,3,4,5,6,7,8,symbol
0,Insider Trading,Relationship,Date,Transaction,Cost,#Shares,Value ($),#Shares Total,SEC Form 4,airt
1,Swenson Nicholas John,CEO,Dec 31,Buy,20.11,"18,617","374,421","937,084",Jan 04 01:09 PM,airt
2,CABILLOT RAYMOND E,Director,Dec 31,Buy,20.11,"18,620","374,481","392,182",Jan 04 01:07 PM,airt
3,CABILLOT RAYMOND E,Director,Dec 30,Buy,20.05,"15,702","314,885","379,148",Dec 31 01:10 PM,airt
4,Swenson Nicholas John,CEO,Dec 30,Buy,19.93,"18,179","362,368","918,467",Dec 31 01:03 PM,airt
5,KOHLER GARY S,Director,Dec 29,Buy,19.06,"38,125","726,654","2,000",Dec 31 06:01 PM,airt
6,CABILLOT RAYMOND E,Director,Dec 29,Buy,18.76,"22,980","431,195","368,157",Dec 31 01:10 PM,airt
7,Swenson Nicholas John,CEO,Dec 29,Buy,18.25,"16,731","305,270","900,288",Dec 31 01:03 PM,airt
8,Swenson Nicholas John,CEO,Mar 23,Buy,11.95,"2,862","34,201","97,800",Mar 23 04:32 PM,airt
9,CABILLOT RAYMOND E,Director,Mar 20,Buy,12.75,174,"2,219","352,071",Mar 23 04:40 PM,airt
10,Swenson Nicholas John,CEO,Mar 19,Buy,10.50,"7,498","78,729","94,938",Mar 20 03:23 PM,airt
11,CABILLOT RAYMOND E,Director,Mar 19,Buy,11.22,"27,400","307,560","351,897",Mar 19 04:57 PM,airt
12,CABILLOT RAYMOND E,Director,Mar 18,Buy,11.33,"11,996","135,942","324,497",Mar 19 04:57 PM,airt
13,Barkett Seth G,Director,Mar 18,Sale,11.52,"2,000","23,030",0,Mar 20 05:28 PM,airt
14,CABILLOT RAYMOND E,Director,Mar 16,Buy,12.22,"16,243","198,408","312,501",Mar 18 09:41 AM,airt
15,CABILLOT RAYMOND E,Director,Mar 12,Buy,15.00,799,"11,985","296,258",Mar 18 09:41 AM,airt
16,Barkett Seth G,Director,Mar 12,Sale,16.00,600,"9,600","2,000",Mar 16 03:38 PM,airt

In [12]:
column_names = inside_trading.loc[0].values # make column headings

In [13]:
inside_trading.columns=column_names # assign column headings
inside_trading

,Insider Trading,Relationship,Date,Transaction,Cost,#Shares,Value ($),#Shares Total,SEC Form 4,airt
0,Insider Trading,Relationship,Date,Transaction,Cost,#Shares,Value ($),#Shares Total,SEC Form 4,airt
1,Swenson Nicholas John,CEO,Dec 31,Buy,20.11,"18,617","374,421","937,084",Jan 04 01:09 PM,airt
2,CABILLOT RAYMOND E,Director,Dec 31,Buy,20.11,"18,620","374,481","392,182",Jan 04 01:07 PM,airt
3,CABILLOT RAYMOND E,Director,Dec 30,Buy,20.05,"15,702","314,885","379,148",Dec 31 01:10 PM,airt
4,Swenson Nicholas John,CEO,Dec 30,Buy,19.93,"18,179","362,368","918,467",Dec 31 01:03 PM,airt
5,KOHLER GARY S,Director,Dec 29,Buy,19.06,"38,125","726,654","2,000",Dec 31 06:01 PM,airt
6,CABILLOT RAYMOND E,Director,Dec 29,Buy,18.76,"22,980","431,195","368,157",Dec 31 01:10 PM,airt
7,Swenson Nicholas John,CEO,Dec 29,Buy,18.25,"16,731","305,270","900,288",Dec 31 01:03 PM,airt
8,Swenson Nicholas John,CEO,Mar 23,Buy,11.95,"2,862","34,201","97,800",Mar 23 04:32 PM,airt
9,CABILLOT RAYMOND E,Director,Mar 20,Buy,12.75,174,"2,219","352,071",Mar 23 04:40 PM,airt
10,Swenson Nicholas John,CEO,Mar 19,Buy,10.50,"7,498","78,729","94,938",Mar 20 03:23 PM,airt
11,CABILLOT RAYMOND E,Director,Mar 19,Buy,11.22,"27,400","307,560","351,897",Mar 19 04:57 PM,airt
12,CABILLOT RAYMOND E,Director,Mar 18,Buy,11.33,"11,996","135,942","324,497",Mar 19 04:57 PM,airt
13,Barkett Seth G,Director,Mar 18,Sale,11.52,"2,000","23,030",0,Mar 20 05:28 PM,airt
14,CABILLOT RAYMOND E,Director,Mar 16,Buy,12.22,"16,243","198,408","312,501",Mar 18 09:41 AM,airt
15,CABILLOT RAYMOND E,Director,Mar 12,Buy,15.00,799,"11,985","296,258",Mar 18 09:41 AM,airt
16,Barkett Seth G,Director,Mar 12,Sale,16.00,600,"9,600","2,000",Mar 16 03:38 PM,airt

In [14]:
inside_trading = inside_trading.rename(columns={symbol:'Symbol'}) # assign symbol heading
inside_trading=inside_trading.loc[inside_trading['Insider Trading']!='Insider Trading'].reset_index(drop=True) # remove first row
inside_trading

,Insider Trading,Relationship,Date,Transaction,Cost,#Shares,Value ($),#Shares Total,SEC Form 4,Symbol
0,Swenson Nicholas John,CEO,Dec 31,Buy,20.11,"18,617","374,421","937,084",Jan 04 01:09 PM,airt
1,CABILLOT RAYMOND E,Director,Dec 31,Buy,20.11,"18,620","374,481","392,182",Jan 04 01:07 PM,airt
2,CABILLOT RAYMOND E,Director,Dec 30,Buy,20.05,"15,702","314,885","379,148",Dec 31 01:10 PM,airt
3,Swenson Nicholas John,CEO,Dec 30,Buy,19.93,"18,179","362,368","918,467",Dec 31 01:03 PM,airt
4,KOHLER GARY S,Director,Dec 29,Buy,19.06,"38,125","726,654","2,000",Dec 31 06:01 PM,airt
5,CABILLOT RAYMOND E,Director,Dec 29,Buy,18.76,"22,980","431,195","368,157",Dec 31 01:10 PM,airt
6,Swenson Nicholas John,CEO,Dec 29,Buy,18.25,"16,731","305,270","900,288",Dec 31 01:03 PM,airt
7,Swenson Nicholas John,CEO,Mar 23,Buy,11.95,"2,862","34,201","97,800",Mar 23 04:32 PM,airt
8,CABILLOT RAYMOND E,Director,Mar 20,Buy,12.75,174,"2,219","352,071",Mar 23 04:40 PM,airt
9,Swenson Nicholas John,CEO,Mar 19,Buy,10.50,"7,498","78,729","94,938",Mar 20 03:23 PM,airt
10,CABILLOT RAYMOND E,Director,Mar 19,Buy,11.22,"27,400","307,560","351,897",Mar 19 04:57 PM,airt
11,CABILLOT RAYMOND E,Director,Mar 18,Buy,11.33,"11,996","135,942","324,497",Mar 19 04:57 PM,airt
12,Barkett Seth G,Director,Mar 18,Sale,11.52,"2,000","23,030",0,Mar 20 05:28 PM,airt
13,CABILLOT RAYMOND E,Director,Mar 16,Buy,12.22,"16,243","198,408","312,501",Mar 18 09:41 AM,airt
14,CABILLOT RAYMOND E,Director,Mar 12,Buy,15.00,799,"11,985","296,258",Mar 18 09:41 AM,airt
15,Barkett Seth G,Director,Mar 12,Sale,16.00,600,"9,600","2,000",Mar 16 03:38 PM,airt